version: '3.1'
services:
  journal_ai_php:
    image: journal_ai_php
    init: true
    build: ./Dockerfile.app
    container_name: journal_ai_php
    tty: true # persist on ports
    ports:
      - "80:80"
    volumes:
      - .:/home/project
    networks:
      static-network:
        ipv4_address: 172.20.0.9
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 192.168.0.1/24
