version: '3.1'
services:
  journal_ai_php:
    image: journal_ai_php
    init: true
    build: .
    container_name: journal_ai_php
    tty: true # persist on ports
    ports:
      - "80:80"
    volumes:
      - .:/var/www/website
